services:
  plex2syslog:
    image: ghcr.io/jakeperalta7/plex2syslog:latest
    container_name: plex2syslog
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - SYSLOG_HOST=host.docker.internal
      - SYSLOG_PORT=514
      - SYSLOG_FACILITY=LOCAL0
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
